name: Java CI with Gradle

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest # 우분투 최신 버전에서

    steps:
    - uses: actions/checkout@v4 # 현재 브랜치의 코드를 actions 서버에 올리기
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # 자바 세팅 actions
      with:
        java-version: '17' # 17버전
        distribution: 'temurin' # JDK 배포판 temurin이 대중적

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # 버전 태그를 사용하는 방식. 최신 v4.x.x 릴리스

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew && ./gradlew build



