name: PR review Bot
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest # 우분투 최신 버전에서
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROMPT: |
            당신은 시니어 Java 백엔드 개발자입니다.
            아래 diff 내용을 리뷰하고 다음 항목을 지적하세요:
            - 잠재적인 버그나 예외 가능성
            - 잘못된 로직, 성능 이슈
            - 읽기 어려운 코드 또는 리팩토링 포인트
            - Clean Code / SOLID 원칙 위반
            문제가 없다고 판단되면 그 이유도 함께 서술하세요.
          LANGUAGE: Korean
          MODEL: gpt-4o